oVirt/releng-tools

- milestones/ovirt-4.5.0.conf
As Sandro explained: "That's the only really needed change in order to
build release notes automatically from git log."
> 4.5.0: Vdsm updated to v4.50.0.6

- milestones/ovirt-4.5.0.conf
- releases/ovirt-4.5.0_alpha1.conf
Since the package is not available in CentOS virt SIG or
ovirt-master-snapshot copr repo I added the package from my
ovirt-imageio-preview repo.
I hope someone can trigger a build in ovirt-master-snapshot, or
add the package to CentOS virt SIG for the next build.
Signed-off-by: Nir Soffer <nsoffer@redhat.com>
> 4.5.0_alpha1: Added ovirt-imageio-2.4.1-1

- milestones/ovirt-4.5.0.conf
https://download.copr.fedorainfracloud.org/results/ovirt/ovirt-master-snapshot/centos-stream-8-x86_64/03708782-ovirt-engine-ui-extensions/ovirt-engine-ui-extensions-1.3.1-1.el8.noarch.rpm
It is not built on CentOS virt SIG yet.
> 4.5.0_alpha1: add ovirt-engine-ui-extensions-1.3.1-1

- milestones/ovirt-4.5.0.conf
https://download.copr.fedorainfracloud.org/results/ovirt/ovirt-master-snapshot/centos-stream-8-x86_64/03710304-ovirt-web-ui/ovirt-web-ui-1.8.0-1.el8.noarch.rpm
It is not built on CentOS virt SIG yet.
> 4.5.0_alpha1: add ovirt-web-ui 1.8.0-1

- pkg_manifest_diff.py
* Increased package name width to 50 characters, to account for longer package names
[y]
> pkg_manifest_diff: Increase package name width to 50 characters

- pkg_manifest_diff.py
* Updated package name width option default to 50 character as well
[y]
> pkg_manifest_diff: Updated the package name width option default

- pkg_manifest_diff.py
* Fix file reading code, that is used for a local manifest, to work for Python3.
[y]
> pkg_manifest_diff: Modified file reading code for Python3

- milestones/ovirt-4.5.0.conf
add ovirt-engine-nodejs-modules-2.2.3-1
https://download.copr.fedorainfracloud.org/results/ovirt/ovirt-master-snapshot/centos-stream-8-x86_64/03911445-ovirt-engine-nodejs-modules/
> 4.5.0: add ovirt-engine-nodejs-modules-2.2.3-1

- milestones/ovirt-4.5.0.conf
add ovirt-engine-ui-extensions-1.3.2-1
https://download.copr.fedorainfracloud.org/results/ovirt/ovirt-master-snapshot/centos-stream-8-x86_64/03912037-ovirt-engine-ui-extensions/
> 4.5.0: add ovirt-engine-ui-extensions-1.3.2-1

- milestones/ovirt-4.5.0.conf
Add ovirt-web-ui 1.8.1-1
https://download.copr.fedorainfracloud.org/results/ovirt/ovirt-master-snapshot/centos-stream-8-x86_64/03912530-ovirt-web-ui/
> 4.5.0: add ovirt-web-ui 1.8.1-1

- milestones/ovirt-4.5.0.conf
Update ovirt-engine-dwh current version to 4.5.2 in /milestones/ovirt-4.5.0.conf 
Signed-off-by: Aviv Litman <alitman@redhat.com>
> 4.5.0: add ovirt-engine-dwh-4.5.2

- release_notes_git.py
* Replace some common RHV wording to oVirt.
[y/n] y
> notes: rebrand docs to oVirt

- milestones/ovirt-4.5.0.conf
Update ovirt-engine-metrics current version to 1.6.0 in /milestones/ovirt-4.5.0.conf
> 4.5.0: add ovirt-engine-metrics-1.6.0

- milestones/ovirt-4.5.0.conf
add ovirt-engine-ui-extensions-1.3.3-1
https://download.copr.fedorainfracloud.org/results/ovirt/ovirt-master-snapshot/centos-stream-8-x86_64/04335111-ovirt-engine-ui-extensions/
> 4.5.0: add ovirt-engine-ui-extensions-1.3.3-1

- releases/ovirt-4.5.1_rc1.conf
* Added link to the copr build of the ovirt-engine-4.5.1.1 to the 4.5.1 RC1 release
[y]
> 4.5.1: Added ovirt-engine-4.5.1.1

- milestones/ovirt-4.5.1.conf
add ovirt-engine-nodejs-modules-2.3.2-2
https://download.copr.fedorainfracloud.org/results/ovirt/ovirt-master-snapshot/centos-stream-8-x86_64/04507561-ovirt-engine-nodejs-modules/
> 4.5.1: add ovirt-engine-nodejs-modules-2.3.2-2

- milestones/ovirt-4.5.1.conf
add ovirt-engine-ui-extensions-1.3.4-1
https://download.copr.fedorainfracloud.org/results/ovirt/ovirt-master-snapshot/centos-stream-8-x86_64/04536774-ovirt-engine-ui-extensions/
> 4.5.1: add ovirt-engine-ui-extensions-1.3.4-1

- milestones/ovirt-4.5.1.conf
Add ovirt-web-ui 1.9.0-1
https://download.copr.fedorainfracloud.org/results/ovirt/ovirt-master-snapshot/centos-stream-8-x86_64/04541664-ovirt-web-ui/
> 4.5.1: add ovirt-web-ui 1.9.0-1

- milestones/ovirt-4.5.2.conf
add ovirt-engine-nodejs-modules-2.3.8-1
https://download.copr.fedorainfracloud.org/results/ovirt/ovirt-master-snapshot/centos-stream-8-x86_64/04661781-ovirt-engine-nodejs-modules/
> 4.5.2: add ovirt-engine-nodejs-modules-2.3.8-1

- milestones/ovirt-4.5.2.conf
add ovirt-engine-ui-extensions-1.3.5-1
https://download.copr.fedorainfracloud.org/results/ovirt/ovirt-master-snapshot/centos-stream-8-x86_64/04662238-ovirt-engine-ui-extensions/
> 4.5.2: add ovirt-engine-ui-extensions-1.3.5-1

- milestones/ovirt-4.5.2.conf
Add ovirt-web-ui 1.9.1-1
https://download.copr.fedorainfracloud.org/results/ovirt/ovirt-master-snapshot/centos-stream-8-x86_64/04671804-ovirt-web-ui/
> 4.5.2: add ovirt-web-ui 1.9.1-1

- milestones/ovirt-4.5.2.conf
add ovirt-engine-nodejs-modules-2.3.9-1
https://download.copr.fedorainfracloud.org/results/ovirt/ovirt-master-snapshot/centos-stream-8-x86_64/04705048-ovirt-engine-nodejs-modules/
> 4.5.2: add ovirt-engine-nodejs-modules-2.3.9-1

- milestones/ovirt-4.5.2.conf
* Updated ovirt-engine version to 4.5.2.5
* Restored the previous version of ovirt-engine-dwh to 4.5.3
[y]
> 4.5.2: Updated ovirt-engine to 4.5.2.5

- milestones/ovirt-4.5.3.conf
add ovirt-engine-ui-extensions-1.3.6-1
https://download.copr.fedorainfracloud.org/results/ovirt/ovirt-master-snapshot/centos-stream-8-x86_64/04877688-ovirt-engine-ui-extensions/
> 4.5.3: add ovirt-engine-ui-extensions-1.3.6-1

- milestones/ovirt-4.5.3.conf
Add ovirt-web-ui 1.9.2-1
https://download.copr.fedorainfracloud.org/results/ovirt/ovirt-master-snapshot/centos-stream-8-x86_64/04882100-ovirt-web-ui/
> 4.5.3: add ovirt-web-ui 1.9.2-1

- milestones/ovirt-4.5.3.conf
add ovirt-engine-nodejs-modules-2.3.10-1
https://download.copr.fedorainfracloud.org/results/ovirt/ovirt-master-snapshot/centos-stream-8-x86_64/04878260-ovirt-engine-nodejs-modules/
> 4.5.3: add ovirt-engine-nodejs-modules-2.3.10-1

- milestones/ovirt-4.5.3.conf
* Fixes:
```
ovirt-release has previous set to ovirt-release-host-node-4.5.3-1
while last known is ovirt-release-host-node-4.5.2-1
```
Signed-off-by: Sandro Bonazzola <sbonazzo@redhat.com>
y
> 4.5.3: fix ovirt-release previous version

- milestones/ovirt-4.5.4.conf
* Re-added bump of ovirt-imageio to v2.4.7 as the tag issue was fixed
[y]
> 4.5.4: Re-added ovirt-imageio-2.4.7

- milestones/ovirt-4.5.5.conf
add ovirt-engine-nodejs-modules-2.3.20-1
https://download.copr.fedorainfracloud.org/results/ovirt/ovirt-master-snapshot/centos-stream-8-x86_64/05147221-ovirt-engine-nodejs-modules/
> 4.5.5: add ovirt-engine-nodejs-modules-2.3.20-1

- milestones/ovirt-4.5.5.conf
add ovirt-engine-ui-extensions-1.3.7-1
https://download.copr.fedorainfracloud.org/results/ovirt/ovirt-master-snapshot/centos-stream-8-x86_64/05153080-ovirt-engine-ui-extensions/
> 4.5.5: add ovirt-engine-ui-extensions-1.3.7-1

- milestones/ovirt-4.5.5.conf
Add ovirt-web-ui 1.9.3-1
https://download.copr.fedorainfracloud.org/results/ovirt/ovirt-master-snapshot/centos-stream-8-x86_64/05154411-ovirt-web-ui/
> 4.5.5: add ovirt-web-ui 1.9.3-1
