milestones/ovirt-4.4.10.conf
milestones/ovirt-4.5.0.conf
releases/ovirt-4.4.10-1.conf

Fixes issue #2
* add ovirt-engine-4.4.10.5 to 4.4.10 as async
[y/n] yes

4.4.10-1: add ovirt-engine-4.4.10.5

---

milestones/ovirt-4.5.0.conf
releases/ovirt-4.5.0_alpha1.conf

* Add ovirt-setup-lib-1.3.3 to 4.5.0_alpha1
[y/n] yes

4.5.0_alpha1: add ovirt-setup-lib-1.3.3

---

milestones/ovirt-4.5.0.conf
releases/ovirt-4.5.0_alpha1.conf

4.5.0_alpha1: add ovirt-hosted-engine-setup-2.6.1

---

milestones/ovirt-4.4.10.conf
milestones/ovirt-4.5.0.conf
releases/ovirt-4.4.10-2.conf

Fixes issue #7
* add ovirt-engine-4.4.10.6 to 4.4.10-2 async
[y/n] y

4.4.10-2: add ovirt-engine-4.4.10.6

---

milestones/ovirt-4.4.10.conf
releases/ovirt-4.4.10-3.conf

* Added ovirt-release44-4.4.10.1
[y]

4.4.10-3: add ovirt-release44-4.4.10.1

---

milestones/ovirt-4.5.0.conf
releases/ovirt-4.5.0_alpha1.conf

* Add ovirt-log-collector-4.4.5 to 4.5.0_alpha1
[y/n] yes

4.5.0_alpha1: add ovirt-log-collector-4.4.5

---

milestones/ovirt-4.4.10.conf

* Add oVirt Node 4.4.10.1 to ovirt-4.4.10
[y/n] yes

ovirt-4.4.10: add node 4.4.10.1

---

milestones/ovirt-4.5.0.conf

* Updated 4.5.0 schedule
[y/n] yes

4.5.0: update schedule

---

milestones/ovirt-4.4.10.conf
releases/ovirt-4.4.10.2.conf

* Prepare for 4.4.10.2
[y/n] yes

ovirt-4.4.10.2: add ovirt-release44-4.4.10.2

---

milestones/ovirt-4.5.0.conf

4.5.0: Vdsm updated to v4.50.0.7

---

milestones/ovirt-4.5.0.conf
releases/ovirt-4.5.0_alpha1.conf

* add imgbased to 4.5.0 alpha 1
[y/n] y

4.5.0_alpha1: add imgbased

---

milestones/ovirt-4.5.0.conf
releases/ovirt-4.5.0_rc1.conf

4.5.0_rc1: add ovirt-engine-dwh-4.5.0

4.5.0_rc1: add ovirt-engine-dwh-4.5.0

---

milestones/ovirt-4.5.0.conf

fix errors reported by github actions
[y/n] yes

4.5.0_alpha1: fix errors reported by github actions

---

milestones/ovirt-4.4.10.conf

* 4.4.10.2: add ovirt-node-ng-image-4.4.10.2
[y/n] y

4.4.10.2: add ovirt-node-ng-image-4.4.10.2

---

milestones/ovirt-4.5.0.conf
releases/ovirt-4.5.0_rc1.conf

4.5.0_rc1: add ovirt-hosted-engine-ha-2.5.0

---

milestones/ovirt-4.4.10.conf
milestones/ovirt-4.5.0.conf
releases/ovirt-4.4.10.2.conf

* Added ovirt-engine-4.4.10.7 to 4.4.10.2 release
[y]

4.4.10.2: Added ovirt-engine-4.4.10.7

---

milestones/ovirt-4.5.0.conf

4.5.0_alpha1: Vdsm updated to v4.50.0.10

---

milestones/ovirt-4.5.0.conf

* update ovirt-ansible-collection to beta 6
[y/n] yes

4.5.0: update ovirt-ansible-collection to beta 6

---

milestones/ovirt-4.5.0.conf

* add ovirt-engine-4.5.0
[y/n] y

4.5.0 add ovirt-engine-4.5.0

---

pkg_manifest_diff.py

* Added support for generating GPG pubkey package diffs.
* That also fixes the issue of utility terminating abnormally in case any GPG pubkey package is added or removed.
[y]

pkg_manifest_diff: Added support for GPG pubkey diff. generation

---

milestones/ovirt-4.5.0.conf

Add ovirt-engine-metrics-1.5.0

ovirt-4.5.0.conf: add ovirt-engine-metrics-1.5.0

---

milestones/ovirt-4.5.0.conf

* 4.5.0: add ovirt-engine-dwh-4.5.1
[y/n] y

4.5.0: add ovirt-engine-dwh-4.5.1

---

milestones/ovirt-4.5.0.conf

* 4.5.0: add cockpit-ovirt-0.16.0
[y/n] y

4.5.0: add cockpit-ovirt-0.16.0

---

milestones/ovirt-4.5.0.conf

4.5.0: add ovirt-imageio-2.4.2

---

milestones/ovirt-4.5.0.conf

4.5.0: Vdsm updated to v4.50.0.11

---

release_notes_git.py

notes: fix generation with proper indentation
[y/n] y

notes: fix generation with proper indentation

---

milestones/ovirt-4.5.0.conf

4.5.0: Vdsm updated to v4.50.0.12

---

milestones/ovirt-4.5.0.conf
milestones/ovirt-4.5.1.conf

* postponed keycloak to 4.5.1
[y/n] y

keycloack postponed to 4.5.1

---

milestones/ovirt-4.5.0.conf

4.5.0: Vdsm updated to v4.50.0.13

---

milestones/ovirt-4.5.0.conf

* 4.5.0: add ovirt-engine-4.5.0.5
[y/n] y

4.5.0: add ovirt-engine-4.5.0.5

---

milestones/ovirt-4.5.0.conf

* Updated ovirt-engine to 4.5.0.7
[y]

4.5.0: Updated ovirt-engine to ovirt-engine-4.5.0.7

---

milestones/ovirt-4.5.0.conf

* add ovirt-dependencies-4.5.2
* add ovirt-engine-4.5.0.8 
[y/n] y

May 11 updates

---

release_notes.template

* Update template post RHEL 8.6 GA
[y/n] y

Update template post RHEL 8.6 GA

---

milestones/ovirt-4.5.0.conf

4.5.0: add 4.5.0.2 async

---

milestones/ovirt-4.5.1.conf

4.5.1: Vdsm updated to v4.50.1.1

---

milestones/ovirt-4.5.1.conf

4.5.1: Vdsm updated to v4.50.1.2

---

milestones/ovirt-4.5.1.conf

* Added ovirt-engine-4.5.1.1
[y]

4.5.1: Added ovirt-engine-4.5.1.1

---

milestones/ovirt-4.5.1.conf

* Updated code freeze date (to June 9th, 2022) and release date (to June 16th, 2022)
[y]

4.5.1 update dates

---

milestones/ovirt-4.5.1.conf

4.5.1: add ovirt-hosted-engine-setup-2.6.4

---

milestones/ovirt-4.5.1.conf

4.5.1: Vdsm updated to v4.50.1.3

---

milestones/ovirt-4.5.1.conf

Vdsm updated to v4.50.1.4

---

milestones/ovirt-4.5.1.conf
releases/ovirt-4.5.1_rc2.conf

* Updated ovirt-engine to 4.5.1.2
[y]

4.5.1: Updated ovirt-engine to 4.5.1.2

---

milestones/ovirt-4.5.1.conf

* Added ovirt-log-collector-4.4.7 to oVirt 4.5.1
[y]

4.5.1: Added ovirt-log-collector-4.4.7

---

release_notes.template

* Updated instructions to include the new centos-release-ovirt45-testing package
[y]

fix template for the split centos-release-ovirt45-testing package

---

milestones/ovirt-4.5.1.conf

* ovirt-engine-keycloak git hash updated to point to 15.0.2-3 release
[y]

4.5.1: Updated ovirt-engine-keycloak to 15.0.2-3

---

milestones/ovirt-4.5.2.conf

4.5.2: Vdsm v4.50.2.1

---

milestones/ovirt-4.5.2.conf

4.5.2: add ovirt-hosted-engine-setup-2.6.5

---

milestones/ovirt-4.5.2.conf

Fixes issue # (delete if not relevant)
https://bugzilla.redhat.com/show_bug.cgi?id=2101474
* Keycloak Administration Console URL displayed in engine-setup summary
[y]

4.5.2: Updated ovirt-engine-keycloak to 15.0.2-4

---

milestones/ovirt-4.5.2.conf

Fixes issue # (delete if not relevant)
https://bugzilla.redhat.com/2090645
* Fix expired SSL certificates validation on connect
* slf4j depedency dropped
[Y]

4.5.2: Updated vdsm-jsonrcp-java to 1.7.2

---

milestones/ovirt-4.5.2.conf

4.5.2: Vdsm v4.50.2.2

---

milestones/ovirt-4.5.2.conf

Signed-off-by: Aviv Litman <alitman@redhat.com>

4.5.2: add ovirt-engine-dwh-4.5.4

---

milestones/ovirt-4.5.2.conf

Signed-off-by: Ori Liel <oliel@redhat.com>
Fixes issue # (delete if not relevant)
*
*
*
[y/n]

update model, metamodel, python-sdk

---

milestones/ovirt-4.5.2.conf

4.5.2: add cockpit-ovirt-0.16.2

---

milestones/ovirt-4.5.2.conf

4.5.2: ovirt-engine-keycloak-15.0.2-5

---

milestones/ovirt-4.5.2.conf

4.5.2: Add ovirt-engine-extension-aaa-ldap-1.4.6

---

milestones/ovirt-4.5.2.conf

4.5.2: Add ovirt-engine-dwh-4.5.5

---

milestones/ovirt-4.5.3.conf

4.5.3: Vdsm v4.50.3.2

---

milestones/ovirt-4.5.3.conf

- 4.5.3: ovirt-engine-dwh-4.5.7-1
- 4.5.3: ovirt-engine-metrics-1.6.1
- 4.5.3: ovirt-engine-extension-aaa-jdbc-1.3.0
- 4.5.3: ovirt-engine-build-dependencies-4.5.3
- 4.5.3: ovirt-engine-keycloak-15.0.2-6

updated pkgs 4.5.3

---

milestones/ovirt-4.5.3.conf

4.5.3: ovirt-ansible-collection-2.3.0-1

---

milestones/ovirt-4.5.3.conf

4.5.3: Vdsm v4.50.3.4

---

milestones/ovirt-4.5.3.conf

4.5.3: otopi-1.10.3

---

milestones/ovirt-4.5.3.conf

4.5.3: ovirt-hosted-engine-setup-2.6.6

---

milestones/ovirt-4.5.2.conf
milestones/ovirt-4.5.3.conf

* Added ovirt-release-host-node 4.5.3.2
[y]

4.5.3 update host node

---

milestones/ovirt-4.5.3.conf

4.5.3: Vdsm v4.50.3.5

---

.github/workflows/check-milestones.yml

* Fix deprecations in GitHub workflow execution
y

check-milestones: fix deprecations

---

milestones/ovirt-4.5.3.conf

4.5.3: ovirt-engine-4.5.3.3

---

milestones/ovirt-4.5.3.conf

- 4.5.3: ovirt-engine-4.5.3.4
- 4.5.3: ovirt-ansible-collection-2.4.0

async 4.5.3 2

---

milestones/ovirt-4.5.4.conf
release_notes_git.py

* Fixes for issues detected in 4.5.4 milestone check
See: https://github.com/oVirt/releng-tools/actions/runs/3584451530/jobs/6031537389
Signed-off-by: Sandro Bonazzola <sbonazzo@redhat.com>
y

fixes for issues detected in 4.5.4 milestone check

---

milestones/ovirt-4.5.4.conf

* 4.5.4: add imgbased-1.2.25
y
Signed-off-by: Sandro Bonazzola <sbonazzo@redhat.com>

4.5.4: add imgbased-1.2.25

---

milestones/ovirt-4.5.4.conf

4.5.4: ovirt-hosted-engine-setup-2.7.0

---

milestones/ovirt-4.5.4.conf

Signed-off-by: Albert Esteve <aesteve@redhat.com>

4.5.4: Add ovirt-imageio 2.4.8

---

milestones/ovirt-4.5.5.conf

* 4.5.5: add ovirt-log-collector-4.5.0
y

4.5.5: add ovirt-log-collector-4.5.0
